dist: trusty
sudo: required
language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - python data/validate.py
after_success:
  - test -n "$TRAVIS_TAG" && python generate.py
